#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 13 15:25:15 2019

@author: lis
"""

subject_interface = {1:'remote',
                     2:'remote',
                     3:'remote',
                     4:'remote',
                     5:'remote',
                     6:'motive',
                     7:'motive',
                     8:'motive',
                     9:'motive',
                     10:'motive',
                     11:'repeated',
                     12:'motive',
                     13:'repeated',
                     14:'motive',
                     15:'remote',
                     16:'motive',
                     17:'motive',
                     18:'motive',
                     19:'motive',
                     20:'motive',
                     21:'motive',
                     22:'motive',
                     23:'motive',
                     24:'motive',
                     25:'motive',
                     26:'motive',
                     27:'remote',
                     28:'motive',
                     29:'motive',
                     30:'motive',
                     31:'remote',
                     32:'motive',
                     33:'motive',
                     34:'motive',
                     35:'',
                     36:'',
                     37:'',
                     38:'',
                     39:'',
                     40:''}

subject_method = {1:'simple',
                     2:'simple',
                     3:'simple',
                     4:'simple',
                     5:'simple',
                     6:'simple',
                     7:'simple',
                     8:'simple',
                     9:'simple',
                     10:'simple',
                     11:'repeated',
                     12:'new',
                     13:'repeated',
                     14:'maxmin',
                     15:'simple',
                     16:'maxmin',
                     17:'new',
                     18:'new',
                     19:'new',
                     20:'maxmin',
                     21:'new',
                     22:'maxmin',
                     23:'maxmin',
                     24:'new',
                     25:'new',
                     26:'simple',
                     27:'simple',
                     28:'new',
                     29:'maxmin',
                     30:'new',
                     31:'simple',
                     32:'maxmin',
                     33:'maxmin',
                     34:'maxmin',
                     35:'',
                     36:'',
                     37:'',
                     38:'',
                     39:'',
                     40:''}